import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import BlogCard from "../components/blog-card";

export const getStaticProps = async () => {
  const res = await fetch(`http://127.0.0.1:8000/api/posts/?format=json`);
  const data = await res.json();

  return {
    props: {
      posts: data || null,
    },
  };
};

const Home = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Marylls Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto prose">
        {/* <main> */}
          {posts && posts.map((post, index) => <BlogCard post={post} />)}
        {/* </main> */}
      </div>
    </div>
  );
};

export default Home;
