import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import dynamic from "next/dynamic";
const BlogCard = dynamic(() => import("../components/blog-card"), {
  ssr: false,
});

export const getStaticProps = async () => {
  const res = await fetch(`https://myblog-production.up.railway.app/api/posts/?format=json`);
  const data = await res.json();

  return {
    props: {
      posts: data || null,
    },
  };
};

const Home = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Marylls Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto prose">
        {posts.map((post, index) => (
          <BlogCard post={post} key={index} />
        ))}
      </div>
    </div>
  );
};

export default Home;
