import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import dynamic from "next/dynamic";
import { config } from '../Constants';
const BlogCard = dynamic(() => import("../components/blog-card"), {
  ssr: false,
});
const { endpoint } = require("@octokit/endpoint");

export const getStaticProps = async () => {
  // var url = config.url.API_URL;
  // const res = await fetch(url.concat(`/api/posts/?format=json`));
  // const data = await res.json();

  const {url, ...options} = endpoint('GET /repos/:owner/:repo/issues', {
    owner: 'llyram',
    repo: 'myblog',
    auth: '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',
  })
  const response = await fetch(url, options)
  const issues = await response.json()
  console.log(issues)

  return {
    props: {
      posts: issues || null,
    },
  };
};



const Home = ({ posts }) => {

  // const [issues, setIssues] = useState([])

  // useEffect(() => {
  //   async function fetchIssues() {
  //     const {url, ...options} = endpoint('GET /repos/:owner/:repo/issues', {
  //       owner: 'llyram',
  //       repo: 'myblog',
  //       auth: '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',
  //     })
  //     const response = await fetch(url, options)
  //     const issues = await response.json()
  //     setIssues(issues)
  //     console.log(issues)
  //   }
  //   fetchIssues()
  // }, [])

  return (
    <div>
      <Head>
        <title>Marylls Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto prose">
        {posts.map((post, index) => (
          <BlogCard post={post} key={index} />
        ))}
      </div>
    </div>
  );
};

export default Home;
